[build]
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/products.json"
  [headers.values]
    Cache-Control = "public, max-age=60"
